In [9]:
import pandas as pd

# Path to your data file
file_path = "crmsample.txt"  # Or .txt if you saved as plain text

# Define column names
columns = [
    "Registration date", "Member Type", "Username", "Fullname", "Line", 
    "Phone", "Contact", "CallDate", "NumOfDays", "AccountStatus", 
    "CallStatus", "Status", "Amount", "CRM1", "CRM2", "Notes"
]

# Read the file
df = pd.read_csv(
    file_path,
    sep="\t",                # Tab-separated
    names=columns,           # Assign our column names
    header=None,             # No header row in file
    quoting=3,               # Keep quotes as-is for multi-line text
    na_values=["null"],      # Convert "null" to NaN
    engine="python"          # More robust parsing for multi-line text
)

# Move Username column to the first position
df = df[["Username"] + [col for col in df.columns if col != "Username"]] 
df.head()

,Username,Registration date,Member Type,Fullname,Line,Phone,Contact,CallDate,NumOfDays,AccountStatus,CallStatus,Status,Amount,CRM1,CRM2,Notes
0,kem8668,4/15/2025,Deposited,NGUYEN THI CHUYEN,xingtg004001,868908299.0,868908299.0,7/27/2025,13.0,Normal,Success,Done,170.0,Bita,NaN,8/1/2025 - Bita - 7/27 khách nạp 170k MGD 17...
1,kem8668,4/15/2025,Deposited,NGUYEN THI CHUYEN,xingtg004001,868908299.0,868908299.0,7/25/2025,15.0,Normal,Success,Done,200.0,Bita,NaN,8/1/2025 - Bita - 7/25 khách nạp 200k MGD 17...
2,kem8668,4/15/2025,Deposited,NGUYEN THI CHUYEN,xingtg004001,868908299.0,868908299.0,7/25/2025,15.0,Normal,Success,Done,500.0,Bita,NaN,8/1/2025 - Bita - 7/25 khách nạp 500k MGD 17...
3,kem8668,4/15/2025,Deposited,NGUYEN THI CHUYEN,xingtg004001,868908299.0,868908299.0,7/23/2025,17.0,Normal,Success,Done,60.0,Bita,NaN,8/1/2025 - Bita - 7/25 khách nạp 60k MGD 175...
4,wingame01,7/17/2025,Non - Deposit,NaN,xingtg0030423,393946307.0,NaN,NaN,7.0,Normal,Call later,Pending,NaN,Tiger,William,""" 08/02/2025 - William - Gọi không nghe máy, g..."